responses:
  - response: "Give me diamonds"
    command:
      console:
        - "give %player% diamond 10"
      player:
        - "say Enjoy your diamonds!"
    perplayer1time: true
  - response: "Tell me a joke"
    command:
      console:
        - "broadcast %player% wants to hear a joke!"
      player:
        - "me Here's a joke for you!"
    perplayer1time: false
